name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      templates: ${{ steps.templates.outputs.templates }}

    steps:
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - run: dotnet new install AElf.ContractTemplates
      - id: templates
        run: | 
          templates=`dotnet new list aelf | grep '\[C#\]' | awk -F '  +' '{print $2}' | paste -sd ','`
          echo "templates=[\"${templates//','/\",\"}\"]" >> $GITHUB_OUTPUT

  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    strategy:
      matrix:
        templates: ${{ needs.job1.outputs.templates }}
    steps:
      - run: echo "Matrix - Project ${{ matrix.templates }}"
